version: "3.9"

services:

  backend:
    image: kimlien-central-api:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - appnet
    container_name: kimlien-central-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      BASE_PATH: "/config/kimlien/KimLienAPI"
      APP_SETTING: "appsettings.json"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    expose:
      - "8080"
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: kimlien-nginx-refactor
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - appnet
    restart: always

networks:
  appnet:
