services:
  customer:
    build:
      context: .
      dockerfile: src/KimLienCustomerView/Dockerfile
    container_name: kimlien-customer
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    volumes:
      - /root/config/kimlien/KimLienCustomerView/appsettings.json:/app/appsettings.json:ro
    expose:
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  administrator:
    build:
      context: .
      dockerfile: src/KimLienAdministrator/Dockerfile
    container_name: kimlien-admin
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
    volumes:
      - /root/config/kimlien/KimLienAdministrator/appsettings.json:/app/appsettings.json:ro
    expose:
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable-alpine
    container_name: kimlien-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customer
      - administrator
